### ISSUE TITLE
For Generative Task

### ISSUE THREAD

**Issue by Zhengsh123** [LZY-the-boys/Twin-Merging#2]
This is a great piece of work. However, after I followed your configuration and set up HELM-Extended-Local for the generative task, I encountered warnings when testing the merged results, such as:
```
WARNING: run spec bbq:subject=all,method=multiple_choice_joint,model=neurips_twin-,max_eval_instances=399 does not have any stat matched by MetricNameMatcher(name='inference_idealized_runtime'split='test', sub_split=None, perturbation_name=None), 0 near misses matching just the name
WARNING: run spec bbq:subject=all,method=multiple_choice_joint,model=neurips_twin-,max_eval_instances=399 does not have any stat matched by MetricNameMatcher(name='inference_denoised_runtime',split='test', sub_split=None, perturbation_name=None), 0 near misses matching just the name
```
It seems that none of the metrics were found. Naturally, the final results were all zero. Do you know what might be causing this issue?

**Comment by LZY-the-boys** [comment]
Thank you for your interest. I am currently a bit busy but will review it in the next few days.

**Comment by Zhengsh123** [comment]
Thank you very much for your reply amidst your busy schedule. I looked into the error, and it seems that the issue is due to not specifying the model during the HELM execution. Is there a missing parameter in your eval.sh script, or did I overlook something?

**Comment by LZY-the-boys** [comment]
> Thank you very much for your reply amidst your busy schedule. I looked into the error, and it seems that the issue is due to not specifying the model during the HELM execution. Is there a missing parameter in your eval.sh script, or did I overlook something?

Sorry again for the delayed response—I was heavily burdened with a paper due. 
I will now take the time to look into this.

**Comment by LZY-the-boys** [comment]
Thank you for bringing this to my attention, I have just ran the code. The warning you encountered is ignorable and does not affect the actual results of the code.

The name `model=neurips_twin-` is set [in this line](https://github.com/LZY-the-boys/Twin-Merging/blob/6c036339ba945609cbc0fde12090a767df5e964a/generative/eval_scripts.sh#L117). This name is used to label the model in logs or outputs, but the actual model performance and behavior remain unaffected.

**Comment by Zhengsh123** [comment]
Thank you very much for your reply. I later realized that the issue was likely with my HELM-Extended-Local configuration, which I have now resolved. This is excellent work, and I look forward to the opportunity to discuss it with you at NeurIPS (if possible).
