### ISSUE TITLE
Fine-tune model scripts.

### ISSUE THREAD

**Issue by FarisXiong** [LZY-the-boys/Twin-Merging#4]
Hi there,
Thank you for the nice work.
I would like to ask if it is convenient for you to share the script for fine-tuning RoBERTa on GLUE.
Thanks for your assistance and support.

**Comment by LZY-the-boys** [comment]
We use the original DARE-Merging repo script for finetuning RoBERTa, you can use https://github.com/yule-BUAA/MergeLM/blob/main/train_plms_glue.py

**Comment by FarisXiong** [comment]
Thanks for your answer.
